name: Publish to Modrinth

on:
  push:
    tags:
      - '*'  # Runs on tag pushes (e.g., v1.0.0)
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Ensure gradlew is executable
        run: chmod +x gradlew  # Fixes permission issue

      - name: Build the Mod
        run: ./gradlew build

      - name: Debug Environment Variables
        run: env | sort  # Prints all environment variables for debugging

      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth --stacktrace --info
